"use client";

import Link from "next/link";
import { ArrowLeft, Check, Copy, Crown, LockKey, Pause, Play, UsersThree, WarningCircle, WifiHigh } from "@phosphor-icons/react";
import { useCallback, useEffect, useRef, useState } from "react";
import { apiRequest } from "@/lib/client/api";
import type { PuzzleSummary, Room, RoomMember } from "@/lib/client/types";
import { movePieceToBoard, resolveDrop, type PositionedPiece } from "@/lib/game/engine";
import { PuzzlePieceArtwork } from "./puzzle-game";
import { useApp } from "./app-provider";

type RoomData = { room: Room; puzzle: PuzzleSummary };
export function RoomPage({ roomId }: { roomId: string }) {
  const { user, requestLogin } = useApp(); const [data, setData] = useState<RoomData>(); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const load = useCallback(() => apiRequest<RoomData>(`/rooms/${roomId}`, {}, user?.id).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "房间加载失败")), [roomId, user?.id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!data || !["waiting", "active"].includes(data.room.status)) return; const timer = window.setInterval(() => void load(), 2000); return () => window.clearInterval(timer); }, [data, load]);
  async function join() { if (!user) { requestLogin(() => undefined); return; } try { await apiRequest(`/rooms/${roomId}/join`, { method: "POST" }, user.id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "加入房间失败"); } }
  async function start() { if (!user) return; try { await apiRequest(`/rooms/${roomId}/start`, { method: "POST" }, user.id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "房间开始失败"); } }
  async function leave() { if (!user) return; await apiRequest(`/rooms/${roomId}/leave`, { method: "POST" }, user.id).catch(() => undefined); window.location.href = "/"; }
  async function copyInvite() { try { await navigator.clipboard.writeText(`${window.location.origin}/room/${roomId}`); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } catch { setError("复制失败，请手动复制当前地址"); } }
  if (error && !data) return <main className="reserved-page"><WarningCircle size={42} /><h1>{error}</h1><Link className="button primary" href="/">返回首页</Link></main>;
  if (!data) return <main className="reserved-page"><UsersThree size={42} /><h1>正在进入房间…</h1></main>;
  const { room, puzzle } = data; const member = user ? room.members.find((item) => item.userId === user.id && !item.leftAt) : undefined;
  return <main className="room-shell"><header className="room-header"><Link href="/" className="icon-button" aria-label="返回发现"><ArrowLeft /></Link><div><p className="eyebrow">多人协作 · 房间 {room.id}</p><h1>{puzzle.title}</h1></div><span className="room-status"><WifiHigh />{room.status === "waiting" ? "等待开始" : room.status === "active" ? "进行中" : room.status === "completed" ? "已完成" : "已结束"}</span><button className="button secondary" onClick={() => void copyInvite()}>{copied ? <Check /> : <Copy />}{copied ? "已复制" : "邀请朋友"}</button><button className="button ghost" onClick={() => void leave()}>离开</button></header>{room.status === "waiting" ? <section className="room-lobby"><div className="room-lobby-main"><UsersThree size={38} /><p className="eyebrow">等朋友加入</p><h2>{room.members.filter((item) => !item.leftAt).length} / 4 人已在房间</h2><p>至少 2 位在线成员后，房主才可以开始。开始后不再接纳新成员，已加入成员可以重连。</p><div className="room-actions"><button className="button primary" disabled={!member || room.ownerId !== user?.id || room.members.filter((item) => !item.leftAt).length < 2} onClick={() => void start()}><Play />开始一起拼</button><button className="button secondary" onClick={() => void copyInvite()}><Copy />复制邀请</button></div></div><MemberList members={room.members} ownerId={room.ownerId} /></section> : room.status === "active" && room.canPlay && room.snapshot ? <RoomBoard room={room} puzzle={puzzle} userId={user?.id ?? ""} onUpdate={(next) => setData((current) => current ? { ...current, room: next } : current)} /> : room.status === "completed" ? <section className="room-result"><TrophyIcon /><p className="eyebrow">协作完成</p><h2>每一片都回到了正确位置</h2><p>参与过移动的成员都会收到一次完成记录和站内通知。</p><Link className="button primary" href="/">返回发现</Link></section> : <section className="room-lobby"><UsersThree size={38} /><h2>加入这个房间一起拼</h2><p>这是一个公开作品的协作房间，登录后即可加入。</p><button className="button primary" onClick={() => void join()}>{user ? "加入房间" : "登录并加入"}</button></section>}{error ? <p className="challenge-error" role="alert"><WarningCircle />{error}</p> : null}</main>;
}

function MemberList({ members, ownerId }: { members: RoomMember[]; ownerId: string }) { return <div className="room-members"><p className="eyebrow">房间成员</p>{members.filter((member) => !member.leftAt).map((member) => <div className="room-member" key={member.userId}><span>{member.displayName.slice(0, 1)}</span><b>{member.displayName}</b>{member.userId === ownerId ? <Crown aria-label="房主" /> : null}<i className={member.online ? "online" : ""} /></div>)}</div>; }

function RoomBoard({ room, puzzle, userId, onUpdate }: { room: Room; puzzle: PuzzleSummary; userId: string; onUpdate: (room: Room) => void }) {
  const boardRef = useRef<HTMLDivElement>(null); const dragRef = useRef<{ pieceId: string; pointerId: number; leaseToken: string; offsetX: number; offsetY: number } | null>(null); const [pieces, setPieces] = useState<PositionedPiece[]>(() => room.snapshot?.pieces ?? []); const [error, setError] = useState("");
  useEffect(() => { setPieces(room.snapshot?.pieces ?? []); }, [room.snapshot, room.stateVersion]);
  async function begin(piece: PositionedPiece, event: React.PointerEvent<HTMLButtonElement>) { if (piece.fixed) return; event.preventDefault(); try { const response = await apiRequest<{ lock: { leaseToken: string } }>(`/rooms/${room.id}/pieces/${piece.id}/lock`, { method: "POST" }, userId); const rect = event.currentTarget.getBoundingClientRect(); dragRef.current = { pieceId: piece.id, pointerId: event.pointerId, leaseToken: response.lock.leaseToken, offsetX: event.clientX - rect.left, offsetY: event.clientY - rect.top }; } catch (reason) { setError(reason instanceof Error ? reason.message : "其他玩家正在移动这块碎片"); } }
  useEffect(() => { function move(event: PointerEvent) { const drag = dragRef.current; const board = boardRef.current; if (!drag || !board || event.pointerId !== drag.pointerId) return; const rect = board.getBoundingClientRect(); const item = pieces.find((piece) => piece.id === drag.pieceId); if (!item) return; setPieces((current) => current.map((piece) => piece.id === item.id ? { ...piece, tray: "board", x: Math.max(0, Math.min(1 - 1 / puzzle.columns, (event.clientX - drag.offsetX - rect.left) / rect.width)), y: Math.max(0, Math.min(1 - 1 / puzzle.rows, (event.clientY - drag.offsetY - rect.top) / rect.height)) } : piece)); }
    async function release(event: PointerEvent) { const drag = dragRef.current; const board = boardRef.current; if (!drag || !board || event.pointerId !== drag.pointerId) return; dragRef.current = null; const rect = board.getBoundingClientRect(); const item = pieces.find((piece) => piece.id === drag.pieceId); if (!item) return; const topLeft = { x: event.clientX - drag.offsetX - rect.left, y: event.clientY - drag.offsetY - rect.top }; const drop = resolveDrop(item, topLeft, { width: rect.width, height: rect.height, rows: puzzle.rows, columns: puzzle.columns }); const next = pieces.map((piece) => piece.id === item.id ? { ...piece, tray: "board" as const, x: drop.x, y: drop.y, fixed: drop.fixed, slot: drop.slot } : piece); setPieces(next); try { const response = await apiRequest<{ room: Room }>(`/rooms/${room.id}/events`, { method: "POST", body: JSON.stringify({ pieceId: item.id, leaseToken: drag.leaseToken, stateVersion: room.stateVersion, piece: next.find((piece) => piece.id === item.id) }) }, userId); onUpdate(response.room); } catch (reason) { setError(reason instanceof Error ? reason.message : "位置同步失败，请稍候重试"); } }
    window.addEventListener("pointermove", move); window.addEventListener("pointerup", release); window.addEventListener("pointercancel", release); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", release); window.removeEventListener("pointercancel", release); };
  }, [pieces, puzzle.columns, puzzle.rows, room.id, room.stateVersion, userId, onUpdate]);
  return <section className="room-play"><div className="room-play-head"><div><p className="eyebrow">共享棋盘</p><h2>每个人看到的是同一局</h2></div><span><LockKey />松手后自动释放碎片锁</span></div><div className="room-board-area"><div ref={boardRef} className="room-board" style={{ aspectRatio: String(puzzle.aspectRatio) }}><div className="target-grid" style={{ gridTemplateColumns: `repeat(${puzzle.columns}, 1fr)`, gridTemplateRows: `repeat(${puzzle.rows}, 1fr)` }} />{pieces.filter((piece) => piece.tray === "board").map((piece) => <button key={piece.id} className={`puzzle-piece on-board ${piece.fixed ? "fixed" : ""}`} type="button" style={{ left: `${(piece.fixed ? piece.column / puzzle.columns : piece.x ?? 0) * 100}%`, top: `${(piece.fixed ? piece.row / puzzle.rows : piece.y ?? 0) * 100}%`, width: `${100 / puzzle.columns}%`, height: `${100 / puzzle.rows}%` }} onPointerDown={(event) => void begin(piece, event)} disabled={piece.fixed}><PuzzlePieceArtwork piece={piece} puzzle={puzzle} /></button>)}</div><div className="room-loose-pieces">{pieces.filter((piece) => piece.tray !== "board").map((piece) => <button key={piece.id} className="puzzle-piece workspace-piece" type="button" style={{ left: `${(piece.x ?? 0) * 100}%`, top: `${(piece.y ?? 0) * 100}%` }} onPointerDown={(event) => void begin(piece, event)}><PuzzlePieceArtwork piece={piece} puzzle={puzzle} /></button>)}</div></div>{error ? <p className="challenge-error" role="alert"><WarningCircle />{error}</p> : null}</section>;
}

function TrophyIcon() { return <Crown size={42} />; }
